name: front tests
on:
  push:
    branches: 
      - main
    paths:
      - frontend/**
  pull_request:
    types: [opened,]
    branches: 
      - main
    paths:
      - frontend/**

  build-check:
    name: Tests - build app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Build nextjs
        run: npm run build
        env:
          CI: true
